### ISSUE TITLE
[Request / Dataset] access to dataset

### ISSUE THREAD

**Issue by YeongHyeon** [aimagelab/art2real#4]
Hi, 

Thank you for providing the datasets.
However, when I try to access, 404 error code appears on web page.

Can I ask you to check whether the server that can access the dataset is active?
Thank you once more.

![image](https://user-images.githubusercontent.com/22256220/223617005-9d7f8e9f-159d-41c6-bd26-7770bbd400ec.png)

**Comment by JunhongH** [comment]
我已成功收到邮件.

**Comment by marcellacornia** [comment]
Hi! I have updated the links in the README file. Now it should work.

**Comment by YeongHyeon** [comment]
Hi @marcellacornia 

It works well now!
Thank you for your support.
